micronaut:
  application:
    name: bamboobot
  server:
    port: 9000
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 2
  http:
    client:
      read-timeout: 30s
  io:
    watch:
      paths: src/main
      restart: true
bamboobot:
  job:
    cron: "0 10 9 ? * MON,TUE,WED,THU,FRI"
